# deploy_app.yaml


- name: "template app file"
  ansible.builtin.template:
    src: "index.j2"
    dest: "/var/www/html/index.nginx-debian.html"
    owner: "root"
    group: "root"
    mode: 0644
#EOF