apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devhouse
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  localhost;
        location / {
          index  index.html index.htm;
        }
        location /pass {
          proxy_pass http://192.168.33.11;
          index  index.html index.htm;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: devhouse
data:
  index.html: |
    <h1>Hello World!</h1>
#EOF